### ISSUE TITLE
Plugin crashes on JDK 7

### ISSUE THREAD

**Issue by nsk-mironov** [nsk-mironov/smuggler#11]
https://travis-ci.org/adelnizamutdinov/kasosalo/builds/118649406

**Comment by nsk-mironov** [comment]
@adelnizamutdinov I've published `0.12.3` update, could you please check if everything works as expected now?

**Comment by adelnizamutdinov** [comment]
works for me https://travis-ci.org/adelnizamutdinov/kasosalo/builds/118654629

**Comment by nsk-mironov** [comment]
Great, thanks.
