### ISSUE TITLE
Smuggler does not work with "non data class" classes

### ISSUE THREAD

**Issue by kingsleyadio** [nsk-mironov/smuggler#17]
I have a normal class with primary constructors, similar in declaration to a data class.

However,
1. I don't need the data class features
2. Some of these classes are open to inheritance, so I can't even use data class

Is there any roadmap for the library that includes this kind of situation?

**Comment by nsk-mironov** [comment]
The library was designed to be used with data classes and I don't have any plans at the moment to support usual  classes. Sorry.
