### ISSUE TITLE
[Bug] Error when try to compile AutoParcelable classes against AS 2.4 preview 7

### ISSUE THREAD

**Issue by stepango** [nsk-mironov/smuggler#22]
Kotlin version: 1.1.2-3
Smuggler version: 0.12.12
Gradle plugin version: 2.4.0-alpha7
Gradle version: 3.5

```* What went wrong:
Execution failed for task ':app:transformClassesWithSmugglerForDebug'.
> expected one element but was: <ImmutableTransformInput{rootLocation=null, jarInputs=[], folderInputs=[ImmutableDirectoryInput{name=857a4b2ebe481e041bc66ef6f8543b1a410df4c8, file=/Users/stepangoncarov/Documents/record-me-android/app/build/intermediates/classes/debug, contentTypes=CLASSES, scopes=PROJECT, changedFiles={}}]}, ImmutableTransformInput{rootLocation=null, jarInputs=[], folderInputs=[]}>
```

**Comment by nsk-mironov** [comment]
Have you tried cleaning the project? I've seen this issue once after updating some of dependencies and cleaning the project helped me. Actually, it looks like an android gradle plugin bug.

**Comment by stepango** [comment]
Yeah, the first thing I tried. Hope it will be fixed until 2.4 release. Thanks.

**Comment by nsk-mironov** [comment]
Ok, I'll try to fix the issue on my side then.

**Comment by nsk-mironov** [comment]
Should be fixed via [ccaedd](https://github.com/nsk-mironov/smuggler/commit/ccaedd4274efbff5eab06e1ca355fb9a720336a9). `0.12.13` is already available in jCenter.

**Comment by stepango** [comment]
Wow. That was fast. Thanks a lot!
