### ISSUE TITLE
How do i ignore something to be not Parcelable?

### ISSUE THREAD

**Issue by rachitmishra** [nsk-mironov/smuggler#26]

**Comment by nsk-mironov** [comment]
Could you elaborate please? Probably with some code sample?

**Comment by rachitmishra** [comment]
Say I have a data class ```data myData(var var1: String, var2: Drawable```, Parceling fails right now as Drawable can't be parceled, I was wondering if we can ignore it somehow? (An alternative might using an id)

**Comment by nsk-mironov** [comment]
What kind of behavior do expect in this case? What value `var2` should be initialized with after deserialization?

**Comment by rachitmishra** [comment]
I would expect some types to be ignored by the plugin

**Comment by nsk-mironov** [comment]
They can't be ignored as they have to be initialized with some value. You can provide a custom `TypeAdapter` that will return some meaningful default value:

```kotlin
@GlobalAdapter
object DrawableAdapter : TypeAdapter<Drawable> {
  override fun toParcel(value: Drawable, parcel: Parcel, flags: Int) = Unit
  override fun fromParcel(parcel: Parcel) = DummyDrawable
}

object DummyDrawable : Drawable() {
  override fun draw(canvas: Canvas) = Unit
  override fun setAlpha(alpha: Int) = Unit
  override fun setColorFilter(filter: ColorFilter?) = Unit
  override fun getOpacity() = PixelFormat.TRANSLUCENT
}
```

Right now I don't have any plans supporting such use case in the library.

**Comment by MobileMon** [comment]
I'd like to have this feature too. I would like to ignore serializing certain properties
