### ISSUE TITLE
doesn't work anymore?

### ISSUE THREAD

**Issue by JozeRi** [nsk-mironov/smuggler#28]
Hey,

this seems like an awesome library, for some reason i can't get it to work.
i followed your installation guide and wrote everything in gradle, but when extending AutoParcelable the compiler require a CREATOR and it's not working..

am i doing something wrong / missing something?

**Comment by adelnizamutdinov** [comment]
it works, the error you're seeing is not the compiler complaining, it's android lint

just ignore the redness, or disable that check in your IDE

**Comment by nsk-mironov** [comment]
Yeah, this is actually a lint warning, not a compiler error. The library works as expected, but lint checks aren't smart enough to recognize the magic the library does.
