### ISSUE TITLE
does it depend on kotlin-reflect?

### ISSUE THREAD

**Issue by adelnizamutdinov** [nsk-mironov/smuggler#9]
Hey, the sample app depends on kotlin-reflect

is it required?

I couldn't get smuggler to work with my app, but I didn't add the kotlin-reflect dependency

**Comment by nsk-mironov** [comment]
Ooop, `kotlin-reflect` has been added to the sample app dependencies by mistake. `Smuggler` doesn't depend on `kotlin-reflect` so it must be something else that stops you from using the library. Do you have any error message or a demo project so I can investigate? Any additional information is much appreciated.

**Comment by adelnizamutdinov** [comment]
I just realized that there's this task `transformClassesWithSmugglerFor` that gets invoked for `assemble`, and does not get invoked for my JVM tests (`testUnitTest`) which verify my `Parcelable` implementations

but even if `transformClassesWithSmugglerFor` does get invoked, it does not get reflected in my `testUnitTest` task, and my `Parcelable` verification tests fail

**Comment by adelnizamutdinov** [comment]
here's the project: https://github.com/adelnizamutdinov/kasosalo/tree/smuggler

a commit that enables the smuggler https://github.com/adelnizamutdinov/kasosalo/commit/7e7d6b214fb8b5aab91d95b86fb54ff744a34719

this test passes since the objects have a manual `Parcelable` implementation https://github.com/adelnizamutdinov/kasosalo/blob/smuggler/app/src/test/kotlin/adeln/zasosalo/screen/ScreensTest.kt#L19-L22

this test https://github.com/adelnizamutdinov/kasosalo/blob/smuggler/app/src/test/kotlin/adeln/zasosalo/screen/ScreensTest.kt#L24-L36 fails with

```
Caused by:
java.lang.UnsupportedOperationException: This method will never be used in runtime. The real implementation will be generated by smuggler plugin.
    at io.mironov.smuggler.AutoParcelable$DefaultImpls.writeToParcel(AutoParcelable.kt:45)
    at adeln.zasosalo.screen.DialogsScreen.writeToParcel(screens.kt:16)
    at com.artemzin.assert_parcelable.AssertParcelable.assertThatObjectParcelable(AssertParcelable.java:32)
```

**Comment by adelnizamutdinov** [comment]
JFYI: smuggler does not work on JDK 7 https://travis-ci.org/adelnizamutdinov/kasosalo/builds/118649406
but that's totally reasonable, will update my travis : )

**Comment by nsk-mironov** [comment]
Thank you for the report. I will try to find out if it's possible to run `smuggler-plugin` for JVM tests. For now, the simplest workaround is to verify `Parcelable` classes using instrumented unit tests. You can check [smuggler-tests](https://github.com/nsk-mironov/smuggler/tree/master/smuggler-samples/smuggler-tests) submodule to see how I test smuggler.

**Comment by nsk-mironov** [comment]
I've created two separate issues #11 and #12. Closing this one.

If you have any questions or additional information, feel free to update #11 and #12.
